#############################################################################
# Generated by PAGE version 4.24.1
#  in conjunction with Tcl version 8.6
#  Sep 29, 2020 02:24:35 PM +0800  platform: Windows NT
set vTcl(timestamp) ""


if {!$vTcl(borrow)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(active_menu_fg) #000000
}



if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    set base .top42
    global vTcl
    set base $vTcl(btop)
    if {$base == ""} {
        set base .top42
    }
    namespace eval ::widgets::$base {
        set dflt,origin 0
        set runvisible 1
    }
    namespace eval ::widgets_bindings {
        set tagslist _TopLevel
    }
    namespace eval ::vTcl::modules::main {
        set procs {
        }
        set compounds {
        }
        set projectType single
    }
}
}


proc vTclWindow.top42 {base} {
    if {$base == ""} {
        set base .top42
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu "$top.m43" -background {#d9d9d9} -highlightbackground {#d9d9d9} \
        -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 724x516+576+207
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1914 1045
    wm minsize $top 152 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "New Toplevel"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    text $top.tex43 \
        -background white -font {-family {Consolas} -size 9} \
        -foreground black -height 200 -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black -state disabled \
        -width 404 -wrap word 
    .top42.tex43 configure -font "-family {Consolas} -size 9"
    .top42.tex43 insert end text
    vTcl:DefineAlias "$top.tex43" "position_text" vTcl:WidgetProc "Toplevel1" 1
    button $top.but44 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 -text X- 
    vTcl:DefineAlias "$top.but44" "X_minus" vTcl:WidgetProc "Toplevel1" 1
    button $top.but45 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 -text X+ 
    vTcl:DefineAlias "$top.but45" "X_plus" vTcl:WidgetProc "Toplevel1" 1
    button $top.but46 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 -text Y+ 
    vTcl:DefineAlias "$top.but46" "Y_plus" vTcl:WidgetProc "Toplevel1" 1
    button $top.but47 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 -text Y- 
    vTcl:DefineAlias "$top.but47" "Y_minus" vTcl:WidgetProc "Toplevel1" 1
    button $top.but48 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 -text Z+ 
    vTcl:DefineAlias "$top.but48" "Z_plus" vTcl:WidgetProc "Toplevel1" 1
    button $top.but49 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 -text Z- 
    vTcl:DefineAlias "$top.but49" "Z_minus" vTcl:WidgetProc "Toplevel1" 1
    button $top.but50 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 -text E+ 
    vTcl:DefineAlias "$top.but50" "E_plus" vTcl:WidgetProc "Toplevel1" 1
    button $top.but51 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 -text E- 
    vTcl:DefineAlias "$top.but51" "E_minus" vTcl:WidgetProc "Toplevel1" 1
    button $top.but52 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -text Rx- 
    vTcl:DefineAlias "$top.but52" "Rx_minus" vTcl:WidgetProc "Toplevel1" 1
    button $top.but53 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -text Rx+ 
    vTcl:DefineAlias "$top.but53" "Rx_plus" vTcl:WidgetProc "Toplevel1" 1
    button $top.but54 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -text Ry- 
    vTcl:DefineAlias "$top.but54" "Ry_minus" vTcl:WidgetProc "Toplevel1" 1
    button $top.but55 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -text Ry+ 
    vTcl:DefineAlias "$top.but55" "Ry_plus" vTcl:WidgetProc "Toplevel1" 1
    button $top.but56 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -text Rz- 
    vTcl:DefineAlias "$top.but56" "Rz_minus" vTcl:WidgetProc "Toplevel1" 1
    button $top.but57 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -text Rz+ 
    vTcl:DefineAlias "$top.but57" "Rz_plus" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.m43
    menu $site_3_0 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#d9d9d9} -font font9 -foreground {#000000} -tearoff 0 
    scale $top.sca44 \
        -activebackground {#ececec} -background {#d9d9d9} -bigincrement 0.0 \
        -font font9 -foreground {#000000} -from 0.0 \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -orient horizontal -resolution 1.0 -showvalue 0 -tickinterval 1.0 \
        -to 2.0 -troughcolor {#d9d9d9} 
    vTcl:DefineAlias "$top.sca44" "speed" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab45 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text Speed: 
    vTcl:DefineAlias "$top.lab45" "Label1" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab46 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -text {1                    5                    10} 
    vTcl:DefineAlias "$top.lab46" "Label2" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab47 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text (deg/s) 
    vTcl:DefineAlias "$top.lab47" "Label3" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab48 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text (mm/s) 
    vTcl:DefineAlias "$top.lab48" "Label4" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab50 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -text {1                   10                   50} 
    vTcl:DefineAlias "$top.lab50" "Label2_1" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab43 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -text {Max. 90mm per move} 
    vTcl:DefineAlias "$top.lab43" "Label5" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab44 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -text {Max. 18deg per move} 
    vTcl:DefineAlias "$top.lab44" "Label6" vTcl:WidgetProc "Toplevel1" 1
    button $top.but58 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#d9d9d9} -command print(\"clicked\") \
        -disabledforeground {#a3a3a3} -font TkDefaultFont \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -pady 0 -text {RESET ALARM} 
    vTcl:DefineAlias "$top.but58" "reset_alarm" vTcl:WidgetProc "Toplevel1" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.tex43 \
        -in $top -x 160 -y 80 -width 404 -relwidth 0 -height 200 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but44 \
        -in $top -x 20 -y 80 -width 60 -relwidth 0 -anchor nw \
        -bordermode ignore 
    place $top.but45 \
        -in $top -x 90 -y 80 -width 60 -relwidth 0 -anchor nw \
        -bordermode ignore 
    place $top.but46 \
        -in $top -x 90 -y 130 -width 60 -relwidth 0 -anchor nw \
        -bordermode ignore 
    place $top.but47 \
        -in $top -x 20 -y 130 -width 60 -relwidth 0 -anchor nw \
        -bordermode ignore 
    place $top.but48 \
        -in $top -x 90 -y 180 -width 60 -relwidth 0 -anchor nw \
        -bordermode ignore 
    place $top.but49 \
        -in $top -x 20 -y 180 -width 60 -relwidth 0 -anchor nw \
        -bordermode ignore 
    place $top.but50 \
        -in $top -x 90 -y 230 -width 60 -relwidth 0 -anchor nw \
        -bordermode ignore 
    place $top.but51 \
        -in $top -x 20 -y 230 -width 60 -relwidth 0 -anchor nw \
        -bordermode ignore 
    place $top.but52 \
        -in $top -x 573 -y 80 -width 60 -relwidth 0 -height 31 -anchor nw \
        -bordermode ignore 
    place $top.but53 \
        -in $top -x 643 -y 80 -width 60 -relwidth 0 -height 31 -anchor nw \
        -bordermode ignore 
    place $top.but54 \
        -in $top -x 573 -y 130 -width 60 -relwidth 0 -height 31 -anchor nw \
        -bordermode ignore 
    place $top.but55 \
        -in $top -x 643 -y 130 -width 60 -relwidth 0 -height 31 -anchor nw \
        -bordermode ignore 
    place $top.but56 \
        -in $top -x 573 -y 180 -width 60 -relwidth 0 -height 31 -anchor nw \
        -bordermode ignore 
    place $top.but57 \
        -in $top -x 643 -y 180 -width 60 -relwidth 0 -height 31 -anchor nw \
        -bordermode ignore 
    place $top.sca44 \
        -in $top -x 220 -y 330 -width 218 -height 23 -anchor nw \
        -bordermode ignore 
    place $top.lab45 \
        -in $top -x 160 -y 328 -width 53 -height 25 -anchor nw \
        -bordermode ignore 
    place $top.lab46 \
        -in $top -x 232 -y 352 -width 203 -relwidth 0 -height 25 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab47 \
        -in $top -x 160 -y 350 -width 57 -relwidth 0 -height 25 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab48 \
        -in $top -x 155 -y 304 -width 67 -relwidth 0 -height 25 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab50 \
        -in $top -x 231 -y 305 -width 203 -relwidth 0 -height 25 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab43 \
        -in $top -x 0 -y 40 -width 173 -relwidth 0 -height 25 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab44 \
        -in $top -x 560 -y 40 -width 163 -relwidth 0 -height 25 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but58 \
        -in $top -x 450 -y 290 -width 120 -relwidth 0 -height 101 \
        -relheight 0 -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top42 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

